name: nodejs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/node

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2.3.2

      - uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Install test server dependencies
        working-directory: ./
        run: npm ci

      - name: Boot test server
        working-directory: ./
        run: make start

      - name: Run tests
        run: npm test

      - name: Cleanup
        working-directory: ./
        run: make stop
